apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - image: webstradev/gatewaytemp:v1
        imagePullPolicy: Always
        name: gateway
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 5
          httpGet:
            path: /healthz
            port: 3000
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /healthz
            port: 3000